backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"

collections:
  - name: "pages"
    label: "Page Demos"
    folder: "_pages"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Iframe URL", name: "iframe_url", widget: "string" }
