backend:
  name: git-gateway
  branch: main # <-- IMPORTANT: This MUST match your repository's branch name

media_folder: "assets/uploads" # Where media files will be stored
public_folder: "/assets/uploads" # The public-facing path to the media files

collections:
  - name: "pages" # The name for the collection in the CMS UI
    label: "Page Demos" # A human-readable name for the collection
    folder: "_pages" # The folder in your repository where files will be saved
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # This will use the title to create the filename
    fields: # The fields for each document
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Layout", name: "layout", widget: "hidden", default: "layout.html" }
      - { label: "URL for Embedded Software", name: "iframe_url", widget: "string" }
